#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FNF_DB")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertPRODUCT(PRODUCT instance);
  partial void UpdatePRODUCT(PRODUCT instance);
  partial void DeletePRODUCT(PRODUCT instance);
  partial void InsertORDER_DETAIL(ORDER_DETAIL instance);
  partial void UpdateORDER_DETAIL(ORDER_DETAIL instance);
  partial void DeleteORDER_DETAIL(ORDER_DETAIL instance);
  partial void InsertORDER_MASTER(ORDER_MASTER instance);
  partial void UpdateORDER_MASTER(ORDER_MASTER instance);
  partial void DeleteORDER_MASTER(ORDER_MASTER instance);
  partial void InsertORDER_STATUS(ORDER_STATUS instance);
  partial void UpdateORDER_STATUS(ORDER_STATUS instance);
  partial void DeleteORDER_STATUS(ORDER_STATUS instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FNF_DBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<PRODUCT> PRODUCTs
	{
		get
		{
			return this.GetTable<PRODUCT>();
		}
	}
	
	public System.Data.Linq.Table<ORDER_DETAIL> ORDER_DETAILs
	{
		get
		{
			return this.GetTable<ORDER_DETAIL>();
		}
	}
	
	public System.Data.Linq.Table<ORDER_MASTER> ORDER_MASTERs
	{
		get
		{
			return this.GetTable<ORDER_MASTER>();
		}
	}
	
	public System.Data.Linq.Table<ORDER_STATUS> ORDER_STATUS
	{
		get
		{
			return this.GetTable<ORDER_STATUS>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCTS")]
public partial class PRODUCT : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ProductNewID;
	
	private string _StyleCode;
	
	private string _MappedChild;
	
	private string _SKUCode;
	
	private string _SKUName;
	
	private string _SKULongDescription;
	
	private string _SKUProductDetails;
	
	private string _SKUClassification;
	
	private string _SKUCategory;
	
	private string _SKUCategoryType;
	
	private string _SKUProductType;
	
	private string _SKUBrand;
	
	private System.Nullable<int> _SpecialPrice;
	
	private System.Nullable<int> _MRP;
	
	private System.Nullable<int> _BaseCost;
	
	private string _SKUStatus;
	
	private string _Size;
	
	private string _Color;
	
	private string _Material;
	
	private string _Inventory;
	
	private string _VendorName;
	
	private string _VendorSKUCode;
	
	private string _OriginCountry;
	
	private string _WashCare;
	
	private string _ShippingReturns;
	
	private string _ProductDiscount;
	
	private string _ProductWeight;
	
	private string _ProductWarranty;
	
	private string _TaxCategory;
	
	private string _MetaTitle;
	
	private string _MetaKeywords;
	
	private string _MetaDescription;
	
	private string _WebsiteSKUStatus;
	
	private string _RecordStatus;
	
	private string _VendorCode;
	
	private string _MOP;
	
	private string _VariantType;
	
	private string _PackQuantity;
	
	private string _CategoryID;
	
	private string _CategoryTypeID;
	
	private string _ProductTypeID;
	
	private string _SizeDataType;
	
	private string _CategoryTypeUrlName;
	
	private string _ColorCode;
	
	private string _PathIndexImage;
	
	private string _PathIndexInternalImage;
	
	private string _PathInternaldetailsSmallImage;
	
	private string _PathInternaldetailsHoverImage;
	
	private string _PathInternaldetailsZoomImage;
	
	private string _PathUpperImage;
	
	private string _PathUpperInternalImage;
	
	private string _PathUpperInternaldetailsSmallImage;
	
	private string _PathUpperInternaldetailsHoverImage;
	
	private string _PathUpperInternaldetailsZoomImage;
	
	private string _PathLowerImage;
	
	private string _PathLowerInternalImage;
	
	private string _PathLowerInternaldetailsSmallImage;
	
	private string _PathLowerInternaldetailsHoverImage;
	
	private string _PathLowerInternaldetailsZoomImage;
	
	private string _PathBackImage;
	
	private string _PathBackInternalImage;
	
	private string _PathBackInternaldetailsSmallImage;
	
	private string _PathBackInternaldetailsHoverImage;
	
	private string _PathBackInternaldetailsZoomImage;
	
	private string _PathDimensionalImage;
	
	private string _PathDimensionalInternalImage;
	
	private string _PathDimensionalInternaldetailsSmallImage;
	
	private string _PathDimensionalInternaldetailsHoverImage;
	
	private string _PathDimensionalInternaldetailsZoomImage;
	
	private string _Dyna_Attribute;
	
	private string _SKUNameHindi;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductNewIDChanging(int value);
    partial void OnProductNewIDChanged();
    partial void OnStyleCodeChanging(string value);
    partial void OnStyleCodeChanged();
    partial void OnMappedChildChanging(string value);
    partial void OnMappedChildChanged();
    partial void OnSKUCodeChanging(string value);
    partial void OnSKUCodeChanged();
    partial void OnSKUNameChanging(string value);
    partial void OnSKUNameChanged();
    partial void OnSKULongDescriptionChanging(string value);
    partial void OnSKULongDescriptionChanged();
    partial void OnSKUProductDetailsChanging(string value);
    partial void OnSKUProductDetailsChanged();
    partial void OnSKUClassificationChanging(string value);
    partial void OnSKUClassificationChanged();
    partial void OnSKUCategoryChanging(string value);
    partial void OnSKUCategoryChanged();
    partial void OnSKUCategoryTypeChanging(string value);
    partial void OnSKUCategoryTypeChanged();
    partial void OnSKUProductTypeChanging(string value);
    partial void OnSKUProductTypeChanged();
    partial void OnSKUBrandChanging(string value);
    partial void OnSKUBrandChanged();
    partial void OnSpecialPriceChanging(System.Nullable<int> value);
    partial void OnSpecialPriceChanged();
    partial void OnMRPChanging(System.Nullable<int> value);
    partial void OnMRPChanged();
    partial void OnBaseCostChanging(System.Nullable<int> value);
    partial void OnBaseCostChanged();
    partial void OnSKUStatusChanging(string value);
    partial void OnSKUStatusChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    partial void OnMaterialChanging(string value);
    partial void OnMaterialChanged();
    partial void OnInventoryChanging(string value);
    partial void OnInventoryChanged();
    partial void OnVendorNameChanging(string value);
    partial void OnVendorNameChanged();
    partial void OnVendorSKUCodeChanging(string value);
    partial void OnVendorSKUCodeChanged();
    partial void OnOriginCountryChanging(string value);
    partial void OnOriginCountryChanged();
    partial void OnWashCareChanging(string value);
    partial void OnWashCareChanged();
    partial void OnShippingReturnsChanging(string value);
    partial void OnShippingReturnsChanged();
    partial void OnProductDiscountChanging(string value);
    partial void OnProductDiscountChanged();
    partial void OnProductWeightChanging(string value);
    partial void OnProductWeightChanged();
    partial void OnProductWarrantyChanging(string value);
    partial void OnProductWarrantyChanged();
    partial void OnTaxCategoryChanging(string value);
    partial void OnTaxCategoryChanged();
    partial void OnMetaTitleChanging(string value);
    partial void OnMetaTitleChanged();
    partial void OnMetaKeywordsChanging(string value);
    partial void OnMetaKeywordsChanged();
    partial void OnMetaDescriptionChanging(string value);
    partial void OnMetaDescriptionChanged();
    partial void OnWebsiteSKUStatusChanging(string value);
    partial void OnWebsiteSKUStatusChanged();
    partial void OnRecordStatusChanging(string value);
    partial void OnRecordStatusChanged();
    partial void OnVendorCodeChanging(string value);
    partial void OnVendorCodeChanged();
    partial void OnMOPChanging(string value);
    partial void OnMOPChanged();
    partial void OnVariantTypeChanging(string value);
    partial void OnVariantTypeChanged();
    partial void OnPackQuantityChanging(string value);
    partial void OnPackQuantityChanged();
    partial void OnCategoryIDChanging(string value);
    partial void OnCategoryIDChanged();
    partial void OnCategoryTypeIDChanging(string value);
    partial void OnCategoryTypeIDChanged();
    partial void OnProductTypeIDChanging(string value);
    partial void OnProductTypeIDChanged();
    partial void OnSizeDataTypeChanging(string value);
    partial void OnSizeDataTypeChanged();
    partial void OnCategoryTypeUrlNameChanging(string value);
    partial void OnCategoryTypeUrlNameChanged();
    partial void OnColorCodeChanging(string value);
    partial void OnColorCodeChanged();
    partial void OnPathIndexImageChanging(string value);
    partial void OnPathIndexImageChanged();
    partial void OnPathIndexInternalImageChanging(string value);
    partial void OnPathIndexInternalImageChanged();
    partial void OnPathInternaldetailsSmallImageChanging(string value);
    partial void OnPathInternaldetailsSmallImageChanged();
    partial void OnPathInternaldetailsHoverImageChanging(string value);
    partial void OnPathInternaldetailsHoverImageChanged();
    partial void OnPathInternaldetailsZoomImageChanging(string value);
    partial void OnPathInternaldetailsZoomImageChanged();
    partial void OnPathUpperImageChanging(string value);
    partial void OnPathUpperImageChanged();
    partial void OnPathUpperInternalImageChanging(string value);
    partial void OnPathUpperInternalImageChanged();
    partial void OnPathUpperInternaldetailsSmallImageChanging(string value);
    partial void OnPathUpperInternaldetailsSmallImageChanged();
    partial void OnPathUpperInternaldetailsHoverImageChanging(string value);
    partial void OnPathUpperInternaldetailsHoverImageChanged();
    partial void OnPathUpperInternaldetailsZoomImageChanging(string value);
    partial void OnPathUpperInternaldetailsZoomImageChanged();
    partial void OnPathLowerImageChanging(string value);
    partial void OnPathLowerImageChanged();
    partial void OnPathLowerInternalImageChanging(string value);
    partial void OnPathLowerInternalImageChanged();
    partial void OnPathLowerInternaldetailsSmallImageChanging(string value);
    partial void OnPathLowerInternaldetailsSmallImageChanged();
    partial void OnPathLowerInternaldetailsHoverImageChanging(string value);
    partial void OnPathLowerInternaldetailsHoverImageChanged();
    partial void OnPathLowerInternaldetailsZoomImageChanging(string value);
    partial void OnPathLowerInternaldetailsZoomImageChanged();
    partial void OnPathBackImageChanging(string value);
    partial void OnPathBackImageChanged();
    partial void OnPathBackInternalImageChanging(string value);
    partial void OnPathBackInternalImageChanged();
    partial void OnPathBackInternaldetailsSmallImageChanging(string value);
    partial void OnPathBackInternaldetailsSmallImageChanged();
    partial void OnPathBackInternaldetailsHoverImageChanging(string value);
    partial void OnPathBackInternaldetailsHoverImageChanged();
    partial void OnPathBackInternaldetailsZoomImageChanging(string value);
    partial void OnPathBackInternaldetailsZoomImageChanged();
    partial void OnPathDimensionalImageChanging(string value);
    partial void OnPathDimensionalImageChanged();
    partial void OnPathDimensionalInternalImageChanging(string value);
    partial void OnPathDimensionalInternalImageChanged();
    partial void OnPathDimensionalInternaldetailsSmallImageChanging(string value);
    partial void OnPathDimensionalInternaldetailsSmallImageChanged();
    partial void OnPathDimensionalInternaldetailsHoverImageChanging(string value);
    partial void OnPathDimensionalInternaldetailsHoverImageChanged();
    partial void OnPathDimensionalInternaldetailsZoomImageChanging(string value);
    partial void OnPathDimensionalInternaldetailsZoomImageChanged();
    partial void OnDyna_AttributeChanging(string value);
    partial void OnDyna_AttributeChanged();
    partial void OnSKUNameHindiChanging(string value);
    partial void OnSKUNameHindiChanged();
    #endregion
	
	public PRODUCT()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductNewID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ProductNewID
	{
		get
		{
			return this._ProductNewID;
		}
		set
		{
			if ((this._ProductNewID != value))
			{
				this.OnProductNewIDChanging(value);
				this.SendPropertyChanging();
				this._ProductNewID = value;
				this.SendPropertyChanged("ProductNewID");
				this.OnProductNewIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleCode", DbType="VarChar(200)")]
	public string StyleCode
	{
		get
		{
			return this._StyleCode;
		}
		set
		{
			if ((this._StyleCode != value))
			{
				this.OnStyleCodeChanging(value);
				this.SendPropertyChanging();
				this._StyleCode = value;
				this.SendPropertyChanged("StyleCode");
				this.OnStyleCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MappedChild", DbType="VarChar(200)")]
	public string MappedChild
	{
		get
		{
			return this._MappedChild;
		}
		set
		{
			if ((this._MappedChild != value))
			{
				this.OnMappedChildChanging(value);
				this.SendPropertyChanging();
				this._MappedChild = value;
				this.SendPropertyChanged("MappedChild");
				this.OnMappedChildChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKUCode", DbType="VarChar(200)")]
	public string SKUCode
	{
		get
		{
			return this._SKUCode;
		}
		set
		{
			if ((this._SKUCode != value))
			{
				this.OnSKUCodeChanging(value);
				this.SendPropertyChanging();
				this._SKUCode = value;
				this.SendPropertyChanged("SKUCode");
				this.OnSKUCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKUName", DbType="VarChar(200)")]
	public string SKUName
	{
		get
		{
			return this._SKUName;
		}
		set
		{
			if ((this._SKUName != value))
			{
				this.OnSKUNameChanging(value);
				this.SendPropertyChanging();
				this._SKUName = value;
				this.SendPropertyChanged("SKUName");
				this.OnSKUNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKULongDescription", DbType="VarChar(MAX)")]
	public string SKULongDescription
	{
		get
		{
			return this._SKULongDescription;
		}
		set
		{
			if ((this._SKULongDescription != value))
			{
				this.OnSKULongDescriptionChanging(value);
				this.SendPropertyChanging();
				this._SKULongDescription = value;
				this.SendPropertyChanged("SKULongDescription");
				this.OnSKULongDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKUProductDetails", DbType="VarChar(MAX)")]
	public string SKUProductDetails
	{
		get
		{
			return this._SKUProductDetails;
		}
		set
		{
			if ((this._SKUProductDetails != value))
			{
				this.OnSKUProductDetailsChanging(value);
				this.SendPropertyChanging();
				this._SKUProductDetails = value;
				this.SendPropertyChanged("SKUProductDetails");
				this.OnSKUProductDetailsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKUClassification", DbType="VarChar(200)")]
	public string SKUClassification
	{
		get
		{
			return this._SKUClassification;
		}
		set
		{
			if ((this._SKUClassification != value))
			{
				this.OnSKUClassificationChanging(value);
				this.SendPropertyChanging();
				this._SKUClassification = value;
				this.SendPropertyChanged("SKUClassification");
				this.OnSKUClassificationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKUCategory", DbType="VarChar(200)")]
	public string SKUCategory
	{
		get
		{
			return this._SKUCategory;
		}
		set
		{
			if ((this._SKUCategory != value))
			{
				this.OnSKUCategoryChanging(value);
				this.SendPropertyChanging();
				this._SKUCategory = value;
				this.SendPropertyChanged("SKUCategory");
				this.OnSKUCategoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKUCategoryType", DbType="VarChar(200)")]
	public string SKUCategoryType
	{
		get
		{
			return this._SKUCategoryType;
		}
		set
		{
			if ((this._SKUCategoryType != value))
			{
				this.OnSKUCategoryTypeChanging(value);
				this.SendPropertyChanging();
				this._SKUCategoryType = value;
				this.SendPropertyChanged("SKUCategoryType");
				this.OnSKUCategoryTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKUProductType", DbType="VarChar(200)")]
	public string SKUProductType
	{
		get
		{
			return this._SKUProductType;
		}
		set
		{
			if ((this._SKUProductType != value))
			{
				this.OnSKUProductTypeChanging(value);
				this.SendPropertyChanging();
				this._SKUProductType = value;
				this.SendPropertyChanged("SKUProductType");
				this.OnSKUProductTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKUBrand", DbType="VarChar(200)")]
	public string SKUBrand
	{
		get
		{
			return this._SKUBrand;
		}
		set
		{
			if ((this._SKUBrand != value))
			{
				this.OnSKUBrandChanging(value);
				this.SendPropertyChanging();
				this._SKUBrand = value;
				this.SendPropertyChanged("SKUBrand");
				this.OnSKUBrandChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecialPrice", DbType="Int")]
	public System.Nullable<int> SpecialPrice
	{
		get
		{
			return this._SpecialPrice;
		}
		set
		{
			if ((this._SpecialPrice != value))
			{
				this.OnSpecialPriceChanging(value);
				this.SendPropertyChanging();
				this._SpecialPrice = value;
				this.SendPropertyChanged("SpecialPrice");
				this.OnSpecialPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRP", DbType="Int")]
	public System.Nullable<int> MRP
	{
		get
		{
			return this._MRP;
		}
		set
		{
			if ((this._MRP != value))
			{
				this.OnMRPChanging(value);
				this.SendPropertyChanging();
				this._MRP = value;
				this.SendPropertyChanged("MRP");
				this.OnMRPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseCost", DbType="Int")]
	public System.Nullable<int> BaseCost
	{
		get
		{
			return this._BaseCost;
		}
		set
		{
			if ((this._BaseCost != value))
			{
				this.OnBaseCostChanging(value);
				this.SendPropertyChanging();
				this._BaseCost = value;
				this.SendPropertyChanged("BaseCost");
				this.OnBaseCostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKUStatus", DbType="VarChar(200)")]
	public string SKUStatus
	{
		get
		{
			return this._SKUStatus;
		}
		set
		{
			if ((this._SKUStatus != value))
			{
				this.OnSKUStatusChanging(value);
				this.SendPropertyChanging();
				this._SKUStatus = value;
				this.SendPropertyChanged("SKUStatus");
				this.OnSKUStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="VarChar(200)")]
	public string Size
	{
		get
		{
			return this._Size;
		}
		set
		{
			if ((this._Size != value))
			{
				this.OnSizeChanging(value);
				this.SendPropertyChanging();
				this._Size = value;
				this.SendPropertyChanged("Size");
				this.OnSizeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(200)")]
	public string Color
	{
		get
		{
			return this._Color;
		}
		set
		{
			if ((this._Color != value))
			{
				this.OnColorChanging(value);
				this.SendPropertyChanging();
				this._Color = value;
				this.SendPropertyChanged("Color");
				this.OnColorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material", DbType="VarChar(200)")]
	public string Material
	{
		get
		{
			return this._Material;
		}
		set
		{
			if ((this._Material != value))
			{
				this.OnMaterialChanging(value);
				this.SendPropertyChanging();
				this._Material = value;
				this.SendPropertyChanged("Material");
				this.OnMaterialChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inventory", DbType="VarChar(200)")]
	public string Inventory
	{
		get
		{
			return this._Inventory;
		}
		set
		{
			if ((this._Inventory != value))
			{
				this.OnInventoryChanging(value);
				this.SendPropertyChanging();
				this._Inventory = value;
				this.SendPropertyChanged("Inventory");
				this.OnInventoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorName", DbType="VarChar(200)")]
	public string VendorName
	{
		get
		{
			return this._VendorName;
		}
		set
		{
			if ((this._VendorName != value))
			{
				this.OnVendorNameChanging(value);
				this.SendPropertyChanging();
				this._VendorName = value;
				this.SendPropertyChanged("VendorName");
				this.OnVendorNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorSKUCode", DbType="VarChar(200)")]
	public string VendorSKUCode
	{
		get
		{
			return this._VendorSKUCode;
		}
		set
		{
			if ((this._VendorSKUCode != value))
			{
				this.OnVendorSKUCodeChanging(value);
				this.SendPropertyChanging();
				this._VendorSKUCode = value;
				this.SendPropertyChanged("VendorSKUCode");
				this.OnVendorSKUCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginCountry", DbType="VarChar(200)")]
	public string OriginCountry
	{
		get
		{
			return this._OriginCountry;
		}
		set
		{
			if ((this._OriginCountry != value))
			{
				this.OnOriginCountryChanging(value);
				this.SendPropertyChanging();
				this._OriginCountry = value;
				this.SendPropertyChanged("OriginCountry");
				this.OnOriginCountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WashCare", DbType="VarChar(200)")]
	public string WashCare
	{
		get
		{
			return this._WashCare;
		}
		set
		{
			if ((this._WashCare != value))
			{
				this.OnWashCareChanging(value);
				this.SendPropertyChanging();
				this._WashCare = value;
				this.SendPropertyChanged("WashCare");
				this.OnWashCareChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingReturns", DbType="VarChar(200)")]
	public string ShippingReturns
	{
		get
		{
			return this._ShippingReturns;
		}
		set
		{
			if ((this._ShippingReturns != value))
			{
				this.OnShippingReturnsChanging(value);
				this.SendPropertyChanging();
				this._ShippingReturns = value;
				this.SendPropertyChanged("ShippingReturns");
				this.OnShippingReturnsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductDiscount", DbType="VarChar(200)")]
	public string ProductDiscount
	{
		get
		{
			return this._ProductDiscount;
		}
		set
		{
			if ((this._ProductDiscount != value))
			{
				this.OnProductDiscountChanging(value);
				this.SendPropertyChanging();
				this._ProductDiscount = value;
				this.SendPropertyChanged("ProductDiscount");
				this.OnProductDiscountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductWeight", DbType="VarChar(200)")]
	public string ProductWeight
	{
		get
		{
			return this._ProductWeight;
		}
		set
		{
			if ((this._ProductWeight != value))
			{
				this.OnProductWeightChanging(value);
				this.SendPropertyChanging();
				this._ProductWeight = value;
				this.SendPropertyChanged("ProductWeight");
				this.OnProductWeightChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductWarranty", DbType="VarChar(200)")]
	public string ProductWarranty
	{
		get
		{
			return this._ProductWarranty;
		}
		set
		{
			if ((this._ProductWarranty != value))
			{
				this.OnProductWarrantyChanging(value);
				this.SendPropertyChanging();
				this._ProductWarranty = value;
				this.SendPropertyChanged("ProductWarranty");
				this.OnProductWarrantyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxCategory", DbType="VarChar(200)")]
	public string TaxCategory
	{
		get
		{
			return this._TaxCategory;
		}
		set
		{
			if ((this._TaxCategory != value))
			{
				this.OnTaxCategoryChanging(value);
				this.SendPropertyChanging();
				this._TaxCategory = value;
				this.SendPropertyChanged("TaxCategory");
				this.OnTaxCategoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaTitle", DbType="VarChar(200)")]
	public string MetaTitle
	{
		get
		{
			return this._MetaTitle;
		}
		set
		{
			if ((this._MetaTitle != value))
			{
				this.OnMetaTitleChanging(value);
				this.SendPropertyChanging();
				this._MetaTitle = value;
				this.SendPropertyChanged("MetaTitle");
				this.OnMetaTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaKeywords", DbType="VarChar(200)")]
	public string MetaKeywords
	{
		get
		{
			return this._MetaKeywords;
		}
		set
		{
			if ((this._MetaKeywords != value))
			{
				this.OnMetaKeywordsChanging(value);
				this.SendPropertyChanging();
				this._MetaKeywords = value;
				this.SendPropertyChanged("MetaKeywords");
				this.OnMetaKeywordsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaDescription", DbType="VarChar(MAX)")]
	public string MetaDescription
	{
		get
		{
			return this._MetaDescription;
		}
		set
		{
			if ((this._MetaDescription != value))
			{
				this.OnMetaDescriptionChanging(value);
				this.SendPropertyChanging();
				this._MetaDescription = value;
				this.SendPropertyChanged("MetaDescription");
				this.OnMetaDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebsiteSKUStatus", DbType="VarChar(200)")]
	public string WebsiteSKUStatus
	{
		get
		{
			return this._WebsiteSKUStatus;
		}
		set
		{
			if ((this._WebsiteSKUStatus != value))
			{
				this.OnWebsiteSKUStatusChanging(value);
				this.SendPropertyChanging();
				this._WebsiteSKUStatus = value;
				this.SendPropertyChanged("WebsiteSKUStatus");
				this.OnWebsiteSKUStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordStatus", DbType="VarChar(20)")]
	public string RecordStatus
	{
		get
		{
			return this._RecordStatus;
		}
		set
		{
			if ((this._RecordStatus != value))
			{
				this.OnRecordStatusChanging(value);
				this.SendPropertyChanging();
				this._RecordStatus = value;
				this.SendPropertyChanged("RecordStatus");
				this.OnRecordStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorCode", DbType="VarChar(100)")]
	public string VendorCode
	{
		get
		{
			return this._VendorCode;
		}
		set
		{
			if ((this._VendorCode != value))
			{
				this.OnVendorCodeChanging(value);
				this.SendPropertyChanging();
				this._VendorCode = value;
				this.SendPropertyChanged("VendorCode");
				this.OnVendorCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOP", DbType="VarChar(100)")]
	public string MOP
	{
		get
		{
			return this._MOP;
		}
		set
		{
			if ((this._MOP != value))
			{
				this.OnMOPChanging(value);
				this.SendPropertyChanging();
				this._MOP = value;
				this.SendPropertyChanged("MOP");
				this.OnMOPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariantType", DbType="VarChar(50)")]
	public string VariantType
	{
		get
		{
			return this._VariantType;
		}
		set
		{
			if ((this._VariantType != value))
			{
				this.OnVariantTypeChanging(value);
				this.SendPropertyChanging();
				this._VariantType = value;
				this.SendPropertyChanged("VariantType");
				this.OnVariantTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackQuantity", DbType="VarChar(50)")]
	public string PackQuantity
	{
		get
		{
			return this._PackQuantity;
		}
		set
		{
			if ((this._PackQuantity != value))
			{
				this.OnPackQuantityChanging(value);
				this.SendPropertyChanging();
				this._PackQuantity = value;
				this.SendPropertyChanged("PackQuantity");
				this.OnPackQuantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", DbType="VarChar(50)")]
	public string CategoryID
	{
		get
		{
			return this._CategoryID;
		}
		set
		{
			if ((this._CategoryID != value))
			{
				this.OnCategoryIDChanging(value);
				this.SendPropertyChanging();
				this._CategoryID = value;
				this.SendPropertyChanged("CategoryID");
				this.OnCategoryIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryTypeID", DbType="VarChar(50)")]
	public string CategoryTypeID
	{
		get
		{
			return this._CategoryTypeID;
		}
		set
		{
			if ((this._CategoryTypeID != value))
			{
				this.OnCategoryTypeIDChanging(value);
				this.SendPropertyChanging();
				this._CategoryTypeID = value;
				this.SendPropertyChanged("CategoryTypeID");
				this.OnCategoryTypeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductTypeID", DbType="VarChar(50)")]
	public string ProductTypeID
	{
		get
		{
			return this._ProductTypeID;
		}
		set
		{
			if ((this._ProductTypeID != value))
			{
				this.OnProductTypeIDChanging(value);
				this.SendPropertyChanging();
				this._ProductTypeID = value;
				this.SendPropertyChanged("ProductTypeID");
				this.OnProductTypeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SizeDataType", DbType="VarChar(50)")]
	public string SizeDataType
	{
		get
		{
			return this._SizeDataType;
		}
		set
		{
			if ((this._SizeDataType != value))
			{
				this.OnSizeDataTypeChanging(value);
				this.SendPropertyChanging();
				this._SizeDataType = value;
				this.SendPropertyChanged("SizeDataType");
				this.OnSizeDataTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryTypeUrlName", DbType="VarChar(100)")]
	public string CategoryTypeUrlName
	{
		get
		{
			return this._CategoryTypeUrlName;
		}
		set
		{
			if ((this._CategoryTypeUrlName != value))
			{
				this.OnCategoryTypeUrlNameChanging(value);
				this.SendPropertyChanging();
				this._CategoryTypeUrlName = value;
				this.SendPropertyChanged("CategoryTypeUrlName");
				this.OnCategoryTypeUrlNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorCode", DbType="VarChar(100)")]
	public string ColorCode
	{
		get
		{
			return this._ColorCode;
		}
		set
		{
			if ((this._ColorCode != value))
			{
				this.OnColorCodeChanging(value);
				this.SendPropertyChanging();
				this._ColorCode = value;
				this.SendPropertyChanged("ColorCode");
				this.OnColorCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathIndexImage", DbType="VarChar(MAX)")]
	public string PathIndexImage
	{
		get
		{
			return this._PathIndexImage;
		}
		set
		{
			if ((this._PathIndexImage != value))
			{
				this.OnPathIndexImageChanging(value);
				this.SendPropertyChanging();
				this._PathIndexImage = value;
				this.SendPropertyChanged("PathIndexImage");
				this.OnPathIndexImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathIndexInternalImage", DbType="VarChar(MAX)")]
	public string PathIndexInternalImage
	{
		get
		{
			return this._PathIndexInternalImage;
		}
		set
		{
			if ((this._PathIndexInternalImage != value))
			{
				this.OnPathIndexInternalImageChanging(value);
				this.SendPropertyChanging();
				this._PathIndexInternalImage = value;
				this.SendPropertyChanged("PathIndexInternalImage");
				this.OnPathIndexInternalImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathInternaldetailsSmallImage", DbType="VarChar(MAX)")]
	public string PathInternaldetailsSmallImage
	{
		get
		{
			return this._PathInternaldetailsSmallImage;
		}
		set
		{
			if ((this._PathInternaldetailsSmallImage != value))
			{
				this.OnPathInternaldetailsSmallImageChanging(value);
				this.SendPropertyChanging();
				this._PathInternaldetailsSmallImage = value;
				this.SendPropertyChanged("PathInternaldetailsSmallImage");
				this.OnPathInternaldetailsSmallImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathInternaldetailsHoverImage", DbType="VarChar(MAX)")]
	public string PathInternaldetailsHoverImage
	{
		get
		{
			return this._PathInternaldetailsHoverImage;
		}
		set
		{
			if ((this._PathInternaldetailsHoverImage != value))
			{
				this.OnPathInternaldetailsHoverImageChanging(value);
				this.SendPropertyChanging();
				this._PathInternaldetailsHoverImage = value;
				this.SendPropertyChanged("PathInternaldetailsHoverImage");
				this.OnPathInternaldetailsHoverImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathInternaldetailsZoomImage", DbType="VarChar(MAX)")]
	public string PathInternaldetailsZoomImage
	{
		get
		{
			return this._PathInternaldetailsZoomImage;
		}
		set
		{
			if ((this._PathInternaldetailsZoomImage != value))
			{
				this.OnPathInternaldetailsZoomImageChanging(value);
				this.SendPropertyChanging();
				this._PathInternaldetailsZoomImage = value;
				this.SendPropertyChanged("PathInternaldetailsZoomImage");
				this.OnPathInternaldetailsZoomImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathUpperImage", DbType="VarChar(MAX)")]
	public string PathUpperImage
	{
		get
		{
			return this._PathUpperImage;
		}
		set
		{
			if ((this._PathUpperImage != value))
			{
				this.OnPathUpperImageChanging(value);
				this.SendPropertyChanging();
				this._PathUpperImage = value;
				this.SendPropertyChanged("PathUpperImage");
				this.OnPathUpperImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathUpperInternalImage", DbType="VarChar(MAX)")]
	public string PathUpperInternalImage
	{
		get
		{
			return this._PathUpperInternalImage;
		}
		set
		{
			if ((this._PathUpperInternalImage != value))
			{
				this.OnPathUpperInternalImageChanging(value);
				this.SendPropertyChanging();
				this._PathUpperInternalImage = value;
				this.SendPropertyChanged("PathUpperInternalImage");
				this.OnPathUpperInternalImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathUpperInternaldetailsSmallImage", DbType="VarChar(MAX)")]
	public string PathUpperInternaldetailsSmallImage
	{
		get
		{
			return this._PathUpperInternaldetailsSmallImage;
		}
		set
		{
			if ((this._PathUpperInternaldetailsSmallImage != value))
			{
				this.OnPathUpperInternaldetailsSmallImageChanging(value);
				this.SendPropertyChanging();
				this._PathUpperInternaldetailsSmallImage = value;
				this.SendPropertyChanged("PathUpperInternaldetailsSmallImage");
				this.OnPathUpperInternaldetailsSmallImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathUpperInternaldetailsHoverImage", DbType="VarChar(MAX)")]
	public string PathUpperInternaldetailsHoverImage
	{
		get
		{
			return this._PathUpperInternaldetailsHoverImage;
		}
		set
		{
			if ((this._PathUpperInternaldetailsHoverImage != value))
			{
				this.OnPathUpperInternaldetailsHoverImageChanging(value);
				this.SendPropertyChanging();
				this._PathUpperInternaldetailsHoverImage = value;
				this.SendPropertyChanged("PathUpperInternaldetailsHoverImage");
				this.OnPathUpperInternaldetailsHoverImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathUpperInternaldetailsZoomImage", DbType="VarChar(MAX)")]
	public string PathUpperInternaldetailsZoomImage
	{
		get
		{
			return this._PathUpperInternaldetailsZoomImage;
		}
		set
		{
			if ((this._PathUpperInternaldetailsZoomImage != value))
			{
				this.OnPathUpperInternaldetailsZoomImageChanging(value);
				this.SendPropertyChanging();
				this._PathUpperInternaldetailsZoomImage = value;
				this.SendPropertyChanged("PathUpperInternaldetailsZoomImage");
				this.OnPathUpperInternaldetailsZoomImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathLowerImage", DbType="VarChar(MAX)")]
	public string PathLowerImage
	{
		get
		{
			return this._PathLowerImage;
		}
		set
		{
			if ((this._PathLowerImage != value))
			{
				this.OnPathLowerImageChanging(value);
				this.SendPropertyChanging();
				this._PathLowerImage = value;
				this.SendPropertyChanged("PathLowerImage");
				this.OnPathLowerImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathLowerInternalImage", DbType="VarChar(MAX)")]
	public string PathLowerInternalImage
	{
		get
		{
			return this._PathLowerInternalImage;
		}
		set
		{
			if ((this._PathLowerInternalImage != value))
			{
				this.OnPathLowerInternalImageChanging(value);
				this.SendPropertyChanging();
				this._PathLowerInternalImage = value;
				this.SendPropertyChanged("PathLowerInternalImage");
				this.OnPathLowerInternalImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathLowerInternaldetailsSmallImage", DbType="VarChar(MAX)")]
	public string PathLowerInternaldetailsSmallImage
	{
		get
		{
			return this._PathLowerInternaldetailsSmallImage;
		}
		set
		{
			if ((this._PathLowerInternaldetailsSmallImage != value))
			{
				this.OnPathLowerInternaldetailsSmallImageChanging(value);
				this.SendPropertyChanging();
				this._PathLowerInternaldetailsSmallImage = value;
				this.SendPropertyChanged("PathLowerInternaldetailsSmallImage");
				this.OnPathLowerInternaldetailsSmallImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathLowerInternaldetailsHoverImage", DbType="VarChar(MAX)")]
	public string PathLowerInternaldetailsHoverImage
	{
		get
		{
			return this._PathLowerInternaldetailsHoverImage;
		}
		set
		{
			if ((this._PathLowerInternaldetailsHoverImage != value))
			{
				this.OnPathLowerInternaldetailsHoverImageChanging(value);
				this.SendPropertyChanging();
				this._PathLowerInternaldetailsHoverImage = value;
				this.SendPropertyChanged("PathLowerInternaldetailsHoverImage");
				this.OnPathLowerInternaldetailsHoverImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathLowerInternaldetailsZoomImage", DbType="VarChar(MAX)")]
	public string PathLowerInternaldetailsZoomImage
	{
		get
		{
			return this._PathLowerInternaldetailsZoomImage;
		}
		set
		{
			if ((this._PathLowerInternaldetailsZoomImage != value))
			{
				this.OnPathLowerInternaldetailsZoomImageChanging(value);
				this.SendPropertyChanging();
				this._PathLowerInternaldetailsZoomImage = value;
				this.SendPropertyChanged("PathLowerInternaldetailsZoomImage");
				this.OnPathLowerInternaldetailsZoomImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathBackImage", DbType="VarChar(MAX)")]
	public string PathBackImage
	{
		get
		{
			return this._PathBackImage;
		}
		set
		{
			if ((this._PathBackImage != value))
			{
				this.OnPathBackImageChanging(value);
				this.SendPropertyChanging();
				this._PathBackImage = value;
				this.SendPropertyChanged("PathBackImage");
				this.OnPathBackImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathBackInternalImage", DbType="VarChar(MAX)")]
	public string PathBackInternalImage
	{
		get
		{
			return this._PathBackInternalImage;
		}
		set
		{
			if ((this._PathBackInternalImage != value))
			{
				this.OnPathBackInternalImageChanging(value);
				this.SendPropertyChanging();
				this._PathBackInternalImage = value;
				this.SendPropertyChanged("PathBackInternalImage");
				this.OnPathBackInternalImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathBackInternaldetailsSmallImage", DbType="VarChar(MAX)")]
	public string PathBackInternaldetailsSmallImage
	{
		get
		{
			return this._PathBackInternaldetailsSmallImage;
		}
		set
		{
			if ((this._PathBackInternaldetailsSmallImage != value))
			{
				this.OnPathBackInternaldetailsSmallImageChanging(value);
				this.SendPropertyChanging();
				this._PathBackInternaldetailsSmallImage = value;
				this.SendPropertyChanged("PathBackInternaldetailsSmallImage");
				this.OnPathBackInternaldetailsSmallImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathBackInternaldetailsHoverImage", DbType="VarChar(MAX)")]
	public string PathBackInternaldetailsHoverImage
	{
		get
		{
			return this._PathBackInternaldetailsHoverImage;
		}
		set
		{
			if ((this._PathBackInternaldetailsHoverImage != value))
			{
				this.OnPathBackInternaldetailsHoverImageChanging(value);
				this.SendPropertyChanging();
				this._PathBackInternaldetailsHoverImage = value;
				this.SendPropertyChanged("PathBackInternaldetailsHoverImage");
				this.OnPathBackInternaldetailsHoverImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathBackInternaldetailsZoomImage", DbType="VarChar(MAX)")]
	public string PathBackInternaldetailsZoomImage
	{
		get
		{
			return this._PathBackInternaldetailsZoomImage;
		}
		set
		{
			if ((this._PathBackInternaldetailsZoomImage != value))
			{
				this.OnPathBackInternaldetailsZoomImageChanging(value);
				this.SendPropertyChanging();
				this._PathBackInternaldetailsZoomImage = value;
				this.SendPropertyChanged("PathBackInternaldetailsZoomImage");
				this.OnPathBackInternaldetailsZoomImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathDimensionalImage", DbType="VarChar(MAX)")]
	public string PathDimensionalImage
	{
		get
		{
			return this._PathDimensionalImage;
		}
		set
		{
			if ((this._PathDimensionalImage != value))
			{
				this.OnPathDimensionalImageChanging(value);
				this.SendPropertyChanging();
				this._PathDimensionalImage = value;
				this.SendPropertyChanged("PathDimensionalImage");
				this.OnPathDimensionalImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathDimensionalInternalImage", DbType="VarChar(MAX)")]
	public string PathDimensionalInternalImage
	{
		get
		{
			return this._PathDimensionalInternalImage;
		}
		set
		{
			if ((this._PathDimensionalInternalImage != value))
			{
				this.OnPathDimensionalInternalImageChanging(value);
				this.SendPropertyChanging();
				this._PathDimensionalInternalImage = value;
				this.SendPropertyChanged("PathDimensionalInternalImage");
				this.OnPathDimensionalInternalImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathDimensionalInternaldetailsSmallImage", DbType="VarChar(MAX)")]
	public string PathDimensionalInternaldetailsSmallImage
	{
		get
		{
			return this._PathDimensionalInternaldetailsSmallImage;
		}
		set
		{
			if ((this._PathDimensionalInternaldetailsSmallImage != value))
			{
				this.OnPathDimensionalInternaldetailsSmallImageChanging(value);
				this.SendPropertyChanging();
				this._PathDimensionalInternaldetailsSmallImage = value;
				this.SendPropertyChanged("PathDimensionalInternaldetailsSmallImage");
				this.OnPathDimensionalInternaldetailsSmallImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathDimensionalInternaldetailsHoverImage", DbType="VarChar(MAX)")]
	public string PathDimensionalInternaldetailsHoverImage
	{
		get
		{
			return this._PathDimensionalInternaldetailsHoverImage;
		}
		set
		{
			if ((this._PathDimensionalInternaldetailsHoverImage != value))
			{
				this.OnPathDimensionalInternaldetailsHoverImageChanging(value);
				this.SendPropertyChanging();
				this._PathDimensionalInternaldetailsHoverImage = value;
				this.SendPropertyChanged("PathDimensionalInternaldetailsHoverImage");
				this.OnPathDimensionalInternaldetailsHoverImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathDimensionalInternaldetailsZoomImage", DbType="VarChar(MAX)")]
	public string PathDimensionalInternaldetailsZoomImage
	{
		get
		{
			return this._PathDimensionalInternaldetailsZoomImage;
		}
		set
		{
			if ((this._PathDimensionalInternaldetailsZoomImage != value))
			{
				this.OnPathDimensionalInternaldetailsZoomImageChanging(value);
				this.SendPropertyChanging();
				this._PathDimensionalInternaldetailsZoomImage = value;
				this.SendPropertyChanged("PathDimensionalInternaldetailsZoomImage");
				this.OnPathDimensionalInternaldetailsZoomImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dyna_Attribute", DbType="VarChar(MAX)")]
	public string Dyna_Attribute
	{
		get
		{
			return this._Dyna_Attribute;
		}
		set
		{
			if ((this._Dyna_Attribute != value))
			{
				this.OnDyna_AttributeChanging(value);
				this.SendPropertyChanging();
				this._Dyna_Attribute = value;
				this.SendPropertyChanged("Dyna_Attribute");
				this.OnDyna_AttributeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKUNameHindi", DbType="VarChar(MAX)")]
	public string SKUNameHindi
	{
		get
		{
			return this._SKUNameHindi;
		}
		set
		{
			if ((this._SKUNameHindi != value))
			{
				this.OnSKUNameHindiChanging(value);
				this.SendPropertyChanging();
				this._SKUNameHindi = value;
				this.SendPropertyChanged("SKUNameHindi");
				this.OnSKUNameHindiChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ORDER_DETAILS")]
public partial class ORDER_DETAIL : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _SKU;
	
	private string _PRODUCT_NAME;
	
	private decimal _UNIT_PRICE;
	
	private int _QTY;
	
	private int _TOTAL;
	
	private int _ORDER_ID;
	
	private EntityRef<ORDER_MASTER> _ORDER_MASTER;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSKUChanging(string value);
    partial void OnSKUChanged();
    partial void OnPRODUCT_NAMEChanging(string value);
    partial void OnPRODUCT_NAMEChanged();
    partial void OnUNIT_PRICEChanging(decimal value);
    partial void OnUNIT_PRICEChanged();
    partial void OnQTYChanging(int value);
    partial void OnQTYChanged();
    partial void OnTOTALChanging(int value);
    partial void OnTOTALChanged();
    partial void OnORDER_IDChanging(int value);
    partial void OnORDER_IDChanged();
    #endregion
	
	public ORDER_DETAIL()
	{
		this._ORDER_MASTER = default(EntityRef<ORDER_MASTER>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKU", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string SKU
	{
		get
		{
			return this._SKU;
		}
		set
		{
			if ((this._SKU != value))
			{
				this.OnSKUChanging(value);
				this.SendPropertyChanging();
				this._SKU = value;
				this.SendPropertyChanged("SKU");
				this.OnSKUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_NAME", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
	public string PRODUCT_NAME
	{
		get
		{
			return this._PRODUCT_NAME;
		}
		set
		{
			if ((this._PRODUCT_NAME != value))
			{
				this.OnPRODUCT_NAMEChanging(value);
				this.SendPropertyChanging();
				this._PRODUCT_NAME = value;
				this.SendPropertyChanged("PRODUCT_NAME");
				this.OnPRODUCT_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_PRICE", DbType="Money NOT NULL")]
	public decimal UNIT_PRICE
	{
		get
		{
			return this._UNIT_PRICE;
		}
		set
		{
			if ((this._UNIT_PRICE != value))
			{
				this.OnUNIT_PRICEChanging(value);
				this.SendPropertyChanging();
				this._UNIT_PRICE = value;
				this.SendPropertyChanged("UNIT_PRICE");
				this.OnUNIT_PRICEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int NOT NULL")]
	public int QTY
	{
		get
		{
			return this._QTY;
		}
		set
		{
			if ((this._QTY != value))
			{
				this.OnQTYChanging(value);
				this.SendPropertyChanging();
				this._QTY = value;
				this.SendPropertyChanged("QTY");
				this.OnQTYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="Int NOT NULL")]
	public int TOTAL
	{
		get
		{
			return this._TOTAL;
		}
		set
		{
			if ((this._TOTAL != value))
			{
				this.OnTOTALChanging(value);
				this.SendPropertyChanging();
				this._TOTAL = value;
				this.SendPropertyChanged("TOTAL");
				this.OnTOTALChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDER_ID", DbType="Int NOT NULL")]
	public int ORDER_ID
	{
		get
		{
			return this._ORDER_ID;
		}
		set
		{
			if ((this._ORDER_ID != value))
			{
				if (this._ORDER_MASTER.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnORDER_IDChanging(value);
				this.SendPropertyChanging();
				this._ORDER_ID = value;
				this.SendPropertyChanged("ORDER_ID");
				this.OnORDER_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ORDER_MASTER_ORDER_DETAIL", Storage="_ORDER_MASTER", ThisKey="ORDER_ID", OtherKey="ID", IsForeignKey=true)]
	public ORDER_MASTER ORDER_MASTER
	{
		get
		{
			return this._ORDER_MASTER.Entity;
		}
		set
		{
			ORDER_MASTER previousValue = this._ORDER_MASTER.Entity;
			if (((previousValue != value) 
						|| (this._ORDER_MASTER.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._ORDER_MASTER.Entity = null;
					previousValue.ORDER_DETAILs.Remove(this);
				}
				this._ORDER_MASTER.Entity = value;
				if ((value != null))
				{
					value.ORDER_DETAILs.Add(this);
					this._ORDER_ID = value.ID;
				}
				else
				{
					this._ORDER_ID = default(int);
				}
				this.SendPropertyChanged("ORDER_MASTER");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ORDER_MASTER")]
public partial class ORDER_MASTER : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private int _ORDER_NO;
	
	private System.DateTime _CREATED_DATE;
	
	private string _PAYMINT_METHOD;
	
	private decimal _AMOUNT;
	
	private decimal _SHIPPING_CHARGE;
	
	private decimal _VAT;
	
	private decimal _TOTAL_AMOUNT;
	
	private int _SHIPPING_ID;
	
	private string _DOCKET_NO;
	
	private EntitySet<ORDER_DETAIL> _ORDER_DETAILs;
	
	private EntitySet<ORDER_STATUS> _ORDER_STATUS;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnORDER_NOChanging(int value);
    partial void OnORDER_NOChanged();
    partial void OnCREATED_DATEChanging(System.DateTime value);
    partial void OnCREATED_DATEChanged();
    partial void OnPAYMINT_METHODChanging(string value);
    partial void OnPAYMINT_METHODChanged();
    partial void OnAMOUNTChanging(decimal value);
    partial void OnAMOUNTChanged();
    partial void OnSHIPPING_CHARGEChanging(decimal value);
    partial void OnSHIPPING_CHARGEChanged();
    partial void OnVATChanging(decimal value);
    partial void OnVATChanged();
    partial void OnTOTAL_AMOUNTChanging(decimal value);
    partial void OnTOTAL_AMOUNTChanged();
    partial void OnSHIPPING_IDChanging(int value);
    partial void OnSHIPPING_IDChanged();
    partial void OnDOCKET_NOChanging(string value);
    partial void OnDOCKET_NOChanged();
    #endregion
	
	public ORDER_MASTER()
	{
		this._ORDER_DETAILs = new EntitySet<ORDER_DETAIL>(new Action<ORDER_DETAIL>(this.attach_ORDER_DETAILs), new Action<ORDER_DETAIL>(this.detach_ORDER_DETAILs));
		this._ORDER_STATUS = new EntitySet<ORDER_STATUS>(new Action<ORDER_STATUS>(this.attach_ORDER_STATUS), new Action<ORDER_STATUS>(this.detach_ORDER_STATUS));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDER_NO", DbType="Int NOT NULL")]
	public int ORDER_NO
	{
		get
		{
			return this._ORDER_NO;
		}
		set
		{
			if ((this._ORDER_NO != value))
			{
				this.OnORDER_NOChanging(value);
				this.SendPropertyChanging();
				this._ORDER_NO = value;
				this.SendPropertyChanged("ORDER_NO");
				this.OnORDER_NOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime NOT NULL")]
	public System.DateTime CREATED_DATE
	{
		get
		{
			return this._CREATED_DATE;
		}
		set
		{
			if ((this._CREATED_DATE != value))
			{
				this.OnCREATED_DATEChanging(value);
				this.SendPropertyChanging();
				this._CREATED_DATE = value;
				this.SendPropertyChanged("CREATED_DATE");
				this.OnCREATED_DATEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYMINT_METHOD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string PAYMINT_METHOD
	{
		get
		{
			return this._PAYMINT_METHOD;
		}
		set
		{
			if ((this._PAYMINT_METHOD != value))
			{
				this.OnPAYMINT_METHODChanging(value);
				this.SendPropertyChanging();
				this._PAYMINT_METHOD = value;
				this.SendPropertyChanged("PAYMINT_METHOD");
				this.OnPAYMINT_METHODChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMOUNT", DbType="Money NOT NULL")]
	public decimal AMOUNT
	{
		get
		{
			return this._AMOUNT;
		}
		set
		{
			if ((this._AMOUNT != value))
			{
				this.OnAMOUNTChanging(value);
				this.SendPropertyChanging();
				this._AMOUNT = value;
				this.SendPropertyChanged("AMOUNT");
				this.OnAMOUNTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHIPPING_CHARGE", DbType="Money NOT NULL")]
	public decimal SHIPPING_CHARGE
	{
		get
		{
			return this._SHIPPING_CHARGE;
		}
		set
		{
			if ((this._SHIPPING_CHARGE != value))
			{
				this.OnSHIPPING_CHARGEChanging(value);
				this.SendPropertyChanging();
				this._SHIPPING_CHARGE = value;
				this.SendPropertyChanged("SHIPPING_CHARGE");
				this.OnSHIPPING_CHARGEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VAT", DbType="Money NOT NULL")]
	public decimal VAT
	{
		get
		{
			return this._VAT;
		}
		set
		{
			if ((this._VAT != value))
			{
				this.OnVATChanging(value);
				this.SendPropertyChanging();
				this._VAT = value;
				this.SendPropertyChanged("VAT");
				this.OnVATChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_AMOUNT", DbType="Money NOT NULL")]
	public decimal TOTAL_AMOUNT
	{
		get
		{
			return this._TOTAL_AMOUNT;
		}
		set
		{
			if ((this._TOTAL_AMOUNT != value))
			{
				this.OnTOTAL_AMOUNTChanging(value);
				this.SendPropertyChanging();
				this._TOTAL_AMOUNT = value;
				this.SendPropertyChanged("TOTAL_AMOUNT");
				this.OnTOTAL_AMOUNTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHIPPING_ID", DbType="Int NOT NULL")]
	public int SHIPPING_ID
	{
		get
		{
			return this._SHIPPING_ID;
		}
		set
		{
			if ((this._SHIPPING_ID != value))
			{
				this.OnSHIPPING_IDChanging(value);
				this.SendPropertyChanging();
				this._SHIPPING_ID = value;
				this.SendPropertyChanged("SHIPPING_ID");
				this.OnSHIPPING_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCKET_NO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string DOCKET_NO
	{
		get
		{
			return this._DOCKET_NO;
		}
		set
		{
			if ((this._DOCKET_NO != value))
			{
				this.OnDOCKET_NOChanging(value);
				this.SendPropertyChanging();
				this._DOCKET_NO = value;
				this.SendPropertyChanged("DOCKET_NO");
				this.OnDOCKET_NOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ORDER_MASTER_ORDER_DETAIL", Storage="_ORDER_DETAILs", ThisKey="ID", OtherKey="ORDER_ID")]
	public EntitySet<ORDER_DETAIL> ORDER_DETAILs
	{
		get
		{
			return this._ORDER_DETAILs;
		}
		set
		{
			this._ORDER_DETAILs.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ORDER_MASTER_ORDER_STATUS", Storage="_ORDER_STATUS", ThisKey="ID", OtherKey="ORDER_ID")]
	public EntitySet<ORDER_STATUS> ORDER_STATUS
	{
		get
		{
			return this._ORDER_STATUS;
		}
		set
		{
			this._ORDER_STATUS.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_ORDER_DETAILs(ORDER_DETAIL entity)
	{
		this.SendPropertyChanging();
		entity.ORDER_MASTER = this;
	}
	
	private void detach_ORDER_DETAILs(ORDER_DETAIL entity)
	{
		this.SendPropertyChanging();
		entity.ORDER_MASTER = null;
	}
	
	private void attach_ORDER_STATUS(ORDER_STATUS entity)
	{
		this.SendPropertyChanging();
		entity.ORDER_MASTER = this;
	}
	
	private void detach_ORDER_STATUS(ORDER_STATUS entity)
	{
		this.SendPropertyChanging();
		entity.ORDER_MASTER = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ORDER_STATUS")]
public partial class ORDER_STATUS : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private int _ORDER_ID;
	
	private string _STATUS;
	
	private System.DateTime _LAST_MODIFIED_DATE;
	
	private string _MODIFIED_BY;
	
	private string _DESCRIPTION;
	
	private EntityRef<ORDER_MASTER> _ORDER_MASTER;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnORDER_IDChanging(int value);
    partial void OnORDER_IDChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnLAST_MODIFIED_DATEChanging(System.DateTime value);
    partial void OnLAST_MODIFIED_DATEChanged();
    partial void OnMODIFIED_BYChanging(string value);
    partial void OnMODIFIED_BYChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    #endregion
	
	public ORDER_STATUS()
	{
		this._ORDER_MASTER = default(EntityRef<ORDER_MASTER>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDER_ID", DbType="Int NOT NULL")]
	public int ORDER_ID
	{
		get
		{
			return this._ORDER_ID;
		}
		set
		{
			if ((this._ORDER_ID != value))
			{
				if (this._ORDER_MASTER.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnORDER_IDChanging(value);
				this.SendPropertyChanging();
				this._ORDER_ID = value;
				this.SendPropertyChanged("ORDER_ID");
				this.OnORDER_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string STATUS
	{
		get
		{
			return this._STATUS;
		}
		set
		{
			if ((this._STATUS != value))
			{
				this.OnSTATUSChanging(value);
				this.SendPropertyChanging();
				this._STATUS = value;
				this.SendPropertyChanged("STATUS");
				this.OnSTATUSChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_MODIFIED_DATE", DbType="DateTime NOT NULL")]
	public System.DateTime LAST_MODIFIED_DATE
	{
		get
		{
			return this._LAST_MODIFIED_DATE;
		}
		set
		{
			if ((this._LAST_MODIFIED_DATE != value))
			{
				this.OnLAST_MODIFIED_DATEChanging(value);
				this.SendPropertyChanging();
				this._LAST_MODIFIED_DATE = value;
				this.SendPropertyChanged("LAST_MODIFIED_DATE");
				this.OnLAST_MODIFIED_DATEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFIED_BY", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string MODIFIED_BY
	{
		get
		{
			return this._MODIFIED_BY;
		}
		set
		{
			if ((this._MODIFIED_BY != value))
			{
				this.OnMODIFIED_BYChanging(value);
				this.SendPropertyChanging();
				this._MODIFIED_BY = value;
				this.SendPropertyChanged("MODIFIED_BY");
				this.OnMODIFIED_BYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string DESCRIPTION
	{
		get
		{
			return this._DESCRIPTION;
		}
		set
		{
			if ((this._DESCRIPTION != value))
			{
				this.OnDESCRIPTIONChanging(value);
				this.SendPropertyChanging();
				this._DESCRIPTION = value;
				this.SendPropertyChanged("DESCRIPTION");
				this.OnDESCRIPTIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ORDER_MASTER_ORDER_STATUS", Storage="_ORDER_MASTER", ThisKey="ORDER_ID", OtherKey="ID", IsForeignKey=true)]
	public ORDER_MASTER ORDER_MASTER
	{
		get
		{
			return this._ORDER_MASTER.Entity;
		}
		set
		{
			ORDER_MASTER previousValue = this._ORDER_MASTER.Entity;
			if (((previousValue != value) 
						|| (this._ORDER_MASTER.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._ORDER_MASTER.Entity = null;
					previousValue.ORDER_STATUS.Remove(this);
				}
				this._ORDER_MASTER.Entity = value;
				if ((value != null))
				{
					value.ORDER_STATUS.Add(this);
					this._ORDER_ID = value.ID;
				}
				else
				{
					this._ORDER_ID = default(int);
				}
				this.SendPropertyChanged("ORDER_MASTER");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
